apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        environment: GoogleCloud
        replicaset: rs0
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: replicaset
                    operator: NotIn
                    values: 
                    - rs0
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--logpath"
            - "/data/db/mongod.log"
            - "--wiredTigerCacheSizeGB"
            - '1'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongod-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongod-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistentstorage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
